{\rtf1\ansi\ansicpg1252\paperw11900\paperh16840\margl0\margr0\margt1440\margb1440\vieww18540\viewh17280\viewscale100\lin0\rin0
{\papercolor16777215}
{\fonttbl\f0\fnil\fcharset0 Helvetica;}
{\colortbl\red0\green0\blue0;\red255\green255\blue255;}
\pard
{\*\pageHeader Helvetica::12px::right::black::0.5::NO::Header Author: Zoe Appleseed [date] - Page [pagenumber] of [totalpages]}
{\*\pageFooter Helvetica::12px::right::black::0.5::NO::Footer Author: Zoe Appleseed [title] - Page [pagenumber] of [totalpages]}
{\*\background {\shp{\*\shpinst\shpleft0\shptop0\shpright0\shpbottom0\shpfhdr0\shpbxmargin\shpbymargin\shpwr0\shpwrk0\shpfblwtxt1\shpz0\shplid1025{\sp{\sn shapeType}{\sv 1}}{\sp{\sn fFlipH}{\sv 0}}{\sp{\sn fFlipV}{\sv 0}}{\sp{\sn fillColor}{\sv 16777215}}{\sp{\sn fFilled}{\sv 1}}{\sp{\sn lineWidth}{\sv 0}}{\sp{\sn fLine}{\sv 0}}{\sp{\sn bWMode}{\sv 9}}{\sp{\sn fBackground}{\sv 1}}}}}

\f0\fs24 \cf0 #Problem 1#(a)mydata - read.delim("consumption.txt", header = TRUE, sep = "")#(b) this code is used to generate graphsplot(  mydata$INC,  mydata$CONS,  main = "Consumption Data",  xlab = "Income",  ylab = "Consumption",  pch = 17,  col = "lightblue3")#(c)mydata[8, 1] - 90detach(mydata)attach(mydata)plot(  INC,  CONS,  main = "Consumption Data",  xlab = "Income",  ylab = "Consumption",  pch = 17,  col = "cadetblue4")#(d)summary(mydata)#(e)cor(mydata)cor(mydata$INC, mydata$CONS)#(f)DCONS - 0.5 * CONSLCONS - log(CONS)INC2 - INC ^ 2SQRTINC - sqrt(INC)#To attach to a data framemydata$DCONS - 0.5 * CONSmydata$LCONS - log(CONS)mydata$INC2 - INC ^ 2mydata$SQRTINC - sqrt(INC)#(G)#Deleting variables from the environment directlyrm(DCONS, SQRTINC)#Deleting variables from the data framemydata - subset(mydata, select = -c(DCONS, SQRTINC))mydata - subset(mydata, select = c(CONS, INC, INC2, LCONS))#(h)rm(list = ls())#Problem 2#(a)fultonfish - read.delim("fultonfish.dat", header = F, sep = "")colnames(fultonfish)[1:4] - c("date", "lprice", "quan", "lquan")#(b)mean(fultonfish$quan)sd(fultonfish$quan)#(c) and (d)t.test(fultonfish$quan, mu = 7200)#we reject H0 if P-value  0.05#(e)attach(fultonfish)plot(lquan, lprice)plot(  lquan,  lprice,  main = "Log Price and Log Quantity",  xlab = "log(Quantity)",  ylab = "log(Price) of Whiting per pound",  pch = 16,  col = "darkred")#to tidy up your code, highlight and then ctrl+shift+acor(lquan, lprice)#(f)save(list = ls(all = TRUE), file = "tutorial01.Rdata")\
}